""" CSV generated by edfringe.com """
CHROME_BOOKMARKS_REGEX = "input/bookmarks_*"

"""URL of favourites with name that was not in the recognised format"""
UNRECOGNISED_FAVOURITES = "generated/unprocessed.txt"

"""Type formatted favourites in 'raw' format"""
FAVOURITE_TS = "../src/raw-favourites.ts"
