""" CSV generated by edfringe.com """
EDFRINGE_FAVOURITES_REGEX = "input/fringe_search_results*"

"""Ratings file"""
RATINGS_FILE = "input/ratings.txt"

"""Booked shows file"""
BOOKINGS_FILE = "input/booked.txt"

"""Booked shows file"""
START_TIMES_FILE = "input/start-times.txt"

"""Unrated shows file"""
UNRATED_FILE = "generated/unrated.txt"

"""Shows with variable start times that do not feature in START_TIMES_FILE"""
UNSET_START_TIME_FILE = "generated/unset-start-times.txt"

"""CSV formatted favourites"""
FAVOURITES_CSV = "generated/favourites.csv"

"""Type formatted favourites in 'raw' format"""
FAVOURITE_TS = "../src/raw-favourites.ts"
