//Generated by Python script
export const favourites = [
["Alex Mason and Freya McGhee: Comedians in STEM", "Laughing Horse @ City Cafe", "1:00", "11:55", "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25", "https://tickets.edfringe.com/whats-on/alex-mason-and-freya-mcghee-comedians-in-stem", "1", false],
["Comedy for the Curious", "Laughing Horse @ The Pear Tree", "1:00", "18:45", "1 2 3 4 5 6 7 8 9 10 11 13 14 15 16 17 18 20 21 22 23 24 25", "https://tickets.edfringe.com/whats-on/comedy-for-the-curious", "-", false],
["Stand-Up Science", "Laughing Horse @ The Pear Tree", "1:00", "17:15", "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25", "https://tickets.edfringe.com/whats-on/stand-up-science", "2", false],
["Time Traveller's Life", "Greenside @ Riddles Court", "0:50", "12:50", "2 3 4 5 6 7 8 9 10 12 13 14 15 16 17 19 20 21 22 23 24", "https://tickets.edfringe.com/whats-on/time-traveller-s-life", "3", false],
] as const;
