//Generated by Python script
export const favourites = [
["16 Postcodes", "Pleasance Courtyard", "1:00", "15:30", "18 19 20 21 22 23 24 25 26", "https://tickets.edfringe.com/whats-on/16-postcodes", "1", false],
["25th Annual Putnam County Spelling Bee", "theSpace @ Niddry St", "1:50", {12:"11:15", 13:"11:15", 14:"11:15", 15:"11:15", 16:"11:15", 19:"11:35", 20:"11:35", 21:"11:35", 22:"11:35", 23:"11:35", }, "17 19 20 21 22 23 24", "https://tickets.edfringe.com/whats-on/25th-annual-putnam-county-spelling-bee", "1", false],
["300 Paintings", "Summerhall", "1:00", "10:55", "18 20 21 22 23 24 25 26", "https://tickets.edfringe.com/whats-on/300-paintings", "2", false],
["1 Dazzling Cabaret", "?", "?", "20:00", "?", "https://www.edfringe.com/tickets/whats-on/1-dazzling-cabaret", "1", false],
["1 Moment in Time", "?", "?", "15:55", "?", "https://www.edfringe.com/tickets/whats-on/1-moment-in-time", "0", false],
["1917: The Woodbine Poet and Padre", "?", "?", "14:15", "?", "https://www.edfringe.com/tickets/whats-on/1917-the-woodbine-poet-and-padre", "1", false],
] as const;
